### PR TITLE
Remove kimchi premium and add Kucoin quoter

### PR DESCRIPTION
**Pull request by mesyakim**
This PR should be merged after [the proposal](https://station.terra.money/proposal/106) passes

### CODE REVIEW

**Comment by YunSuk-Yeo** [comment]
https://github.com/terra-money/oracle-feeder/blob/db8b36ef55bb0a0f8e3c23e78d620737eeb3a921/price-server/src/prices.ts#L31-L35

The filter is enforcing to select `USD/USDT`, but the calculation expects `USDT/USD`.
Maybe L31 should use `getBaseCurrency`?

**Comment by YunSuk-Yeo** [comment]
https://github.com/terra-money/oracle-feeder/blob/db8b36ef55bb0a0f8e3c23e78d620737eeb3a921/price-server/src/prices.ts#L31

Seems current cryptoProvider config does not contains any `some/USDT`

**Comment by mesyakim** [comment]
> https://github.com/terra-money/oracle-feeder/blob/db8b36ef55bb0a0f8e3c23e78d620737eeb3a921/price-server/src/prices.ts#L29-L31
> 
> Seems current cryptoProvider config does not contain any `some/USDT`.

It is not required by default. This feature is made for special cases.

**Review by YunSuk-Yeo — APPROVED** [review]
LGTM

I just added some changes in default-sample.js and README.md

**Pull request merged**
